# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_uploader:
        class: OnlineShopBundle\FileUploader
        arguments: ["%images_directory%"]
#    app.doctrine_image_listener:
#        class: OnlineShopBundle\EventListener\ImageUploadListener
#        arguments: ['@app.image_uploader']
#        tags:
#            - { name: doctrine.event_listener, event: prePersist}
#            - { name: doctrine.event_listener, event: preUpdate}
#            - { name: doctrine.event_listener, event: postLoad}
#    service_name:
#        class: OnlineShopBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    product.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - \OnlineShopBundle\Entity\ProductPromotion
    category.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - \OnlineShopBundle\Entity\CategoryPromotion
    promotion_manager:
        class: OnlineShopBundle\Service\PromotionManager
        arguments: ['@product.promotions', '@category.promotions']
    price_calculator:
        class: OnlineShopBundle\Service\PriceCalculator
        arguments: ['@promotion_manager']
