<?php

namespace OnlineShopBundle\Repository;

/**
 * CategoryPromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchActiveCategoryPromotions()
    {
        $qb = $this->createQueryBuilder('cp');

        $today = new \DateTime();

        $qb->select('cp')
            ->where($qb->expr()->lte('cp.startDate', ':today'))
            ->andWhere($qb->expr()->gte('cp.endDate', ':today'))
            ->setParameter(':today', $today->format('Y-m-d'));

        $results = $qb->getQuery()->getResult();

        return $results;
    }

}
