<?php

namespace OnlineShopBundle\Repository;
use OnlineShopBundle\Entity\Category;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAvailableProducts()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT p
            FROM OnlineShopBundle:Product p
            WHERE p.price > :price
            ORDER BY p.price ASC'
        )->setParameter('price', 0)->getResult();
    }

    public function findProductByCategory(Category $category)
    {
        $db = $this->createQueryBuilder('p');
        $db->select('p')
            ->where($db->expr()->eq('p.category', ':category'))
            ->andWhere($db->expr()->gt('p.quantity', 0))
            ->orderBy('p.price', 'ASC')
            ->setParameter('category', $category);

        return $db->getQuery()->getResult();
    }
}
