<?php

namespace OnlineShopBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAvailableProducts()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT p
            FROM OnlineShopBundle:Product p
            WHERE p.price > :price
            ORDER BY p.price ASC'
        )->setParameter('price', 0)->getResult();
    }
}
