<?php

namespace OnlineShopBundle\Repository;

/**
 * ProductPromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchActiveProductPromotions()
    {
        $qb = $this->createQueryBuilder('pp');

        $today = new \DateTime();

        $qb->select('pp')
            ->where($qb->expr()->lte('pp.startData', ':today'))
            ->andWhere($qb->expr()->gte('pp.endData', ':today'))
            ->setParameter(':today', $today->format('Y-m-d'));

        $results = $qb->getQuery()->getResult();

        return $results;
    }
}
