<?php

namespace OnlineShopBundle\Repository;

/**
 * UserStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
